### ISSUE TITLE
ArchLinux aur已打包

### ISSUE THREAD

**Issue by levinit** [racklin/moedict-desktop#19]
包名 [moedict](https://aur.archlinux.org/packages/moedict/)
使用yaourt安装`yaourt -S moedict`

**Comment by ghost** [comment]
謝謝!

安裝時, 看到:
"==> Starting package()...
文件較大，請耐心等待。Please wating..."

不確定是源代碼還是 PKGBUILD 的信息, "Wating" 語法和拼寫錯誤, 應是 "Please wait..."

**Comment by levinit** [comment]
@nemolus  
我自己加的提示 请等待 因为真的很大....
后面拼写是我的错 我改改
